# default configuration
baseURL = "http://examplesite.com"
languageCode = "en-us"
summaryLength = "10"
theme = "acamilo.github.io"
title = ""

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

#[[menu.main]]
#URL = "blog"
#name = "Blog"
#weight = 2

[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3

#[[menu.main]]
#URL = "contact"
#name = "Contact"
#weight = 4


# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#0047ba"
# contact info
phone = "1 917 929 6293"
email = "alex.camilo+p@gmail.com"
address = "44 portland st, FL 6, Worcester MA, 01609"
# meta description
author = "Alex Camilo"
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyright &copy; 2020 Alex Camilo"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = false
form_action = "#" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-facebook"
URL = "#"

[[params.social]]
icon = "ti-instagram"
URL = "#"

[[params.social]]
icon = "ti-dribbble"
URL = "#"

[[params.social]]
icon = "ti-twitter-alt"
URL = "#"